INSERT INTO User (username, password) VALUES ('ABird96', 'pass123');
INSERT INTO User (username, password) VALUES ('JSmitth02', 'pass321');
INSERT INTO User (username, password) VALUES ('SamBird98', 'ilovemaths');
INSERT INTO Deck (name, description, owner, studyType) VALUES ('French vocab', 'The French words I need to learn for my holiday to France.', 1, 1);
INSERT INTO Deck (name, description, owner, studyType) VALUES ('WW2 facts', 'Facts about WW2 I need to learn for my upcoming History exam.', 3, 1);
INSERT INTO Deck (name, description, owner, studyType) VALUES ('Spanish vocab', 'The Spanish words I need to learn for my upcoming Spanish exam.', 1, 1);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('In which year did the war start?', '1939', '2019-06-17', 2, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('In which year did the war end?', '1945', '2019-06-17', 2, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is hello in French?', 'bonjour', '2019-06-17', 1, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is goodbye in French?', 'au revoir', '2019-06-17', 1, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is hello in Spanish?', 'hola', '2019-06-17', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is goodbye in Spanish?', 'adios', '2019-06-17', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is my name is Aaron in Spanish', 'mi nombre es Aaron', '2019-06-18', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is dog in Spanish?', 'perro', '2019-06-17', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is cat in Spanish?', 'gato', '2018-06-01', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is how are you in Spanish', 'como estas?', '2019-04-10', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is blue in Spanish?', 'azul', '2019-06-17', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is green in Spanish?', 'verde', '2018-06-01', 3, 0);
INSERT INTO Card (question, answer, revisionDate, deckId, level) VALUES ('What is red in Spanish', 'rodo', '2019-04-10', 3, 0);